require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe CareerStagesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # CareerStage. As you add validations to CareerStage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CareerStagesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all career_stages as @career_stages" do
      career_stage = CareerStage.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:career_stages)).to eq([career_stage])
    end
  end

  describe "GET show" do
    it "assigns the requested career_stage as @career_stage" do
      career_stage = CareerStage.create! valid_attributes
      get :show, {:id => career_stage.to_param}, valid_session
      expect(assigns(:career_stage)).to eq(career_stage)
    end
  end

  describe "GET new" do
    it "assigns a new career_stage as @career_stage" do
      get :new, {}, valid_session
      expect(assigns(:career_stage)).to be_a_new(CareerStage)
    end
  end

  describe "GET edit" do
    it "assigns the requested career_stage as @career_stage" do
      career_stage = CareerStage.create! valid_attributes
      get :edit, {:id => career_stage.to_param}, valid_session
      expect(assigns(:career_stage)).to eq(career_stage)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CareerStage" do
        expect {
          post :create, {:career_stage => valid_attributes}, valid_session
        }.to change(CareerStage, :count).by(1)
      end

      it "assigns a newly created career_stage as @career_stage" do
        post :create, {:career_stage => valid_attributes}, valid_session
        expect(assigns(:career_stage)).to be_a(CareerStage)
        expect(assigns(:career_stage)).to be_persisted
      end

      it "redirects to the created career_stage" do
        post :create, {:career_stage => valid_attributes}, valid_session
        expect(response).to redirect_to(CareerStage.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved career_stage as @career_stage" do
        post :create, {:career_stage => invalid_attributes}, valid_session
        expect(assigns(:career_stage)).to be_a_new(CareerStage)
      end

      it "re-renders the 'new' template" do
        post :create, {:career_stage => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested career_stage" do
        career_stage = CareerStage.create! valid_attributes
        put :update, {:id => career_stage.to_param, :career_stage => new_attributes}, valid_session
        career_stage.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested career_stage as @career_stage" do
        career_stage = CareerStage.create! valid_attributes
        put :update, {:id => career_stage.to_param, :career_stage => valid_attributes}, valid_session
        expect(assigns(:career_stage)).to eq(career_stage)
      end

      it "redirects to the career_stage" do
        career_stage = CareerStage.create! valid_attributes
        put :update, {:id => career_stage.to_param, :career_stage => valid_attributes}, valid_session
        expect(response).to redirect_to(career_stage)
      end
    end

    describe "with invalid params" do
      it "assigns the career_stage as @career_stage" do
        career_stage = CareerStage.create! valid_attributes
        put :update, {:id => career_stage.to_param, :career_stage => invalid_attributes}, valid_session
        expect(assigns(:career_stage)).to eq(career_stage)
      end

      it "re-renders the 'edit' template" do
        career_stage = CareerStage.create! valid_attributes
        put :update, {:id => career_stage.to_param, :career_stage => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested career_stage" do
      career_stage = CareerStage.create! valid_attributes
      expect {
        delete :destroy, {:id => career_stage.to_param}, valid_session
      }.to change(CareerStage, :count).by(-1)
    end

    it "redirects to the career_stages list" do
      career_stage = CareerStage.create! valid_attributes
      delete :destroy, {:id => career_stage.to_param}, valid_session
      expect(response).to redirect_to(career_stages_url)
    end
  end

end
